### ISSUE TITLE
config.toml how to change player location on windows?

### ISSUE THREAD

**Issue by Lukasz88PL** [akiirui/mpv-handler#10]
Hello, I tried to change it to:
player = "C:\Programy\mpv"
player = "C:/Programy/mpv"

In first one I get: 
```
Error: Failed to decode config file:
C:\Programy\mpv\config.toml: invalid escape character in string: `P` at line 12 column 14
```

And in the second one:
`Error: Failed to run downloader "mpv": Access denied. (os error 5)`

So what's the proper way?

**Comment by akiirui** [comment]
Hello, see [README#Custom Configuration](https://github.com/akiirui/mpv-handler/blob/main/README.md#custom-configuration)

```toml
# For Windows users,
# The path format can be "C:\\folder\\some.exe" or "C:/folder/some.exe"
```

The first one `\`(Backslash) needs escape as `\\`

**Comment by Lukasz88PL** [comment]
Thank you!

**Comment by akiirui** [comment]
@Lukasz88PL And I recommend you to custom configuration with `custom.toml`, the `config.toml` will be overwritten when update mpv-handler.
