### ISSUE TITLE
Error when using open in mpv

### ISSUE THREAD

**Issue by i-ideamama** [akiirui/mpv-handler#12]
I get this error in the terminal whenever i click in MPV icon - 
> "Error: Failed to convert video URL string: invalid utf-8 sequence of 1 bytes from index 2" 
>
Using on: Brave Browser on Debian 11 stable with violent monkey
any help would be appreciated

**Comment by akiirui** [comment]
Please show me these informations:

- The video URL when this error occurred.
- The base64 encoded URL (right click on the mpv icon to copy)
- `config.toml` & `custom.toml` (if you created it)

**Comment by i-ideamama** [comment]
- There was no specific video URL where this happened. Every time i tried it with a YouTube video, it didnt work
- right clicking the MPV icon didnt do anything
- `# Don't edit this file!
# This is default settings, It will be overwritten when mpv-handler is updated.
#
# For customize settings, create and edit file:
# - Linux:
#     - $HOME/.config/mpv-handler/custom.toml
#     - /etc/mpv-handler/custom.toml
#   If the first one is found, the second one will not be loaded.
# - Windows:  custom.toml (in the same directory as mpv-handler.exe)

### Player ###
player = "/usr/bin/mpv"

### Video Downloader ###
[mpv]
bin = "/usr/bin/mpv"
cookies = "--ytdl-raw-options-append=cookies="
cookies_prefix = true
play_mode = "direct"
quality.best = "--ytdl-format=bestvideo+bestaudio/best"
quality.2160p = "--ytdl-format=bestvideo[height<=2160]+bestaudio/best[height<=2160]/best"
quality.1440p = "--ytdl-format=bestvideo[height<=1440]+bestaudio/best[height<=1440]/best"
quality.1080p = "--ytdl-format=bestvideo[height<=1080]+bestaudio/best[height<=1080]/best"
quality.720p = "--ytdl-format=bestvideo[height<=720]+bestaudio/best[height<=720]/best"
quality.480p = "--ytdl-format=bestvideo[height<=480]+bestaudio/best[height<=480]/best"
quality.360p = "--ytdl-format=bestvideo[height<=360]+bestaudio/best[height<=360]/best"
`

**Comment by akiirui** [comment]
> right clicking the MPV icon didnt do anything

Right click the mpv icon in the video page, and click "Copy link address"

**Comment by i-ideamama** [comment]
This is the link address: `mpv://aHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g/dj1GS0JaX3NRNVdIMA==/?downloader=mpv&quality=best`

Tried it with this video: `https://www.youtube.com/watch?v=FKBZ_sQ5WH0`.

**Comment by akiirui** [comment]
> This is the link address: `mpv://aHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g/dj1GS0JaX3NRNVdIMA==/?downloader=mpv&quality=best`
> 
> Tried it with this video: `https://www.youtube.com/watch?v=FKBZ_sQ5WH0`.

Thanks for reply, but I couldn't reproduce with this link address and the video URL.

The base64 encoded data is valid, encoding from UTF-8.

One more point. this error is from function `String::from_utf8`, but it's behind function `base64::decode`. If base64 data include invalid utf-8 bytes, then the error should come from `base64::decode`.

I don't know why `String::from_utf8` thinks the decoded UTF-8 bytes is invalid.

If you can help me to debug this error, i will compile a debug build for you.

**Comment by akiirui** [comment]
Here is a debug build, [mpv-handler-debug.zip](https://github.com/akiirui/mpv-handler/files/7192326/mpv-handler-debug.zip)

Please run:

```bash
./mpv-handler 'mpv://aHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g/dj1GS0JaX3NRNVdIMA==/?downloader=mpv&quality=best'
```

And paste its output here, thanks.

**Comment by pcoopergit** [comment]
Duplicate issue... https://github.com/akiirui/mpv-handler/issues/11

**Comment by akiirui** [comment]
Fixed in https://github.com/akiirui/mpv-handler/commit/50bdcb68d586e58c77875b9e18f5e341506d4f98
