### ISSUE TITLE
Option to use vlc://*url* instead of mpv://play/*url*

### ISSUE THREAD

**Issue by Zabijak05** [akiirui/mpv-handler#18]
Hi there, it would be really helpful if I could use a different url for opening things in mpv. I use a third-party web site that already has set up vlc://*url* buttons and seems too much of a challenge for me to do it alone...

**Comment by Zabijak05** [comment]
I am not sure if I am allowed to share the name of the website, as they try to keep the community in a manageable size..

**Comment by akiirui** [comment]
> I am not sure if I am allowed to share the name of the website, as they try to keep the community in a manageable size..

Emm, so I can't help you anymore. 
Because I don't know the `vlc://URL` format and its html element. Cannot write a userscript for you.

But you have other ways, you can use vlc to play videos from that site directly.

😅
