### ISSUE TITLE
如果需要拉取视频中的字幕需要用什么指令？

### ISSUE THREAD

**Issue by yubanmeiqin9048** [akiirui/mpv-handler#19]

**Comment by akiirui** [comment]
ytdl-hook 默认就会获取字幕并添加到 mpv 中

**Comment by akiirui** [comment]
如果你想使用  youtube-dl 下载视频字幕，参见 https://github.com/ytdl-org/youtube-dl#subtitle-options
此咨询应该与 mpv-handler 无关。
