### ISSUE TITLE
能添加代理配置,观看youtube吗

### ISSUE THREAD

**Issue by Miraclei** [akiirui/mpv-handler#20]
大佬，在windows 下怎么通过本地代理观看youtube视频

**Comment by akiirui** [comment]
不清楚你使用的代理方式，没办法回答（

**Comment by Z-fly** [comment]
应该是用proxifier吧

**Comment by akiirui** [comment]
> 应该是用proxifier吧

他也没回复，代理方式太多了我也不知道啊。。。

No reply for a long time, closed.
