### ISSUE TITLE
Add support for yt-dlp

### ISSUE THREAD

**Issue by mica** [akiirui/mpv-handler#21]
It seems youtube-dl is being throttled, with downloads taking much longer than with the actively developed fork called [yt-dlp](https://github.com/yt-dlp/yt-dlp). Could you look into getting it working with mpv-handler?

**Comment by akiirui** [comment]
It's already support yt-dlp.

By default, mpv-handler uses `downloader - mpv`, mpv uses `ytdl-hook`.

If the yt-dlp binary file is found, the latest mpv will use yt-dlp.

https://github.com/mpv-player/mpv/commit/cc4ada655aae06218b900bb434e3521566394cde#diff-66b4f14afc23c2b0ba76ecd3f2b760acb4eb11e968b1d16877e6d3d4e3ad6c4f

**Comment by mica** [comment]
Ok great! Thanks 😄
