### ISSUE TITLE
Windows config.toml set to /usr/bin/mpv, causing error 

### ISSUE THREAD

**Issue by mica** [akiirui/mpv-handler#22]
The config is causing this error: `"Failed to run downloader "mpv": The system cannot find the file specified. (os error 2)"`

All is well after editing these lines to:
```
bin = "mpv"
player = "mpv"
```
Not sure if this is relevant, but I have mpv installed via chocolatey

**Comment by akiirui** [comment]
Please see 
[README - Windows - Manual installation](https://github.com/akiirui/mpv-handler#manual-installation-1) and [README - Configuration - Custom configuration](https://github.com/akiirui/mpv-handler#custom-configuration)

**Comment by mica** [comment]
Perhaps for the Windows download, you could include a different config.toml with just "mpv" instead of "/usr/bin/mpv"? It would cut out the extra step of having to edit the file.

**Comment by akiirui** [comment]
> Perhaps for the Windows download, you could include a different config.toml with just "mpv" instead of "/usr/bin/mpv"? It would cut out the extra step of having to edit the file.

Okay, I will do it at next release.

But it isn't useful for most Windows users (because they're not add mpv to the `PATH` environment variables).

Currently, you can manually modify their values to your want.

**Comment by mica** [comment]
Thanks, it will be great for those of us who do have mpv added to the path. I install mpv via chocolatey, which does add it: https://community.chocolatey.org/packages/mpv

Speaking of which, do you have any interest in making mpv-handler available as a chocolatey package?

**Comment by akiirui** [comment]
> Speaking of which, do you have any interest in making mpv-handler available as a chocolatey package?

Maybe... After the mpv-handler config file stabilization

(Because the config file will be changed in the next release. I want to keep it simple and stupid)
