### ISSUE TITLE
Error: Downloader or player exited with error or termination signal

### ISSUE THREAD

**Issue by Neomanbeta** [akiirui/mpv-handler#23]
不好意思又是我。
这两天突然就报这个错误用不了了。
我把play with mpv的脚本升级到最新了(2022.03.24)
又重新装了一遍mpv-handler。
mpv也用updater.bat把版本和youtube-dl升级到最新了。
我也检查了，我的custom.toml依然存在，里面的mpv路径也没变过。
实在挠头不知道哪里出了问题。

**Comment by akiirui** [comment]
是观看 bilibili 的视频时出错么？
mpv + yt-dlp 最近在观看 bilibili 时会 403。这是上游的问题，我这里没法儿解决。。。

你可以在 Console 里手动 mpv "bilibili视频链接" 就能看到 403 报错.

**Comment by Neomanbeta** [comment]
是YouTube，twitch，bilibili都这样了，所以我才来问的。

**Comment by kazumi513** [comment]
我遇到了一个非常类似的问题。

**Comment by akiirui** [comment]
@Neomanbeta @kazumi513 

你们如果是 Windows 的话，尝试把 custom.toml 里 

```
[mpv]
bin = "mpv.exe"
```

改为

```
[mpv]
bin = "mpv.com"
```

`mpv.com` 带有命令行输出，可以了解是那一个地方出错了。

**Comment by akiirui** [comment]
And one more question: What the version of your youtube-dl?
youtube-dl 2021.12.17 or yt-dlp 2022.04.08?

**Comment by Neomanbeta** [comment]
custom.toml里的mpv.exe改成mpv.com以后console里的信息如下：
Playing: https://www.youtube.com/watch?v=uk2ou5gt_94&t=328s
[ytdl_hook] Traceback (most recent call last):
[ytdl_hook]   File "__main__.py", line 19, in <module>
[ytdl_hook]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\__init__.py", line 475, in main
[ytdl_hook]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\__init__.py", line 468, in _real_main
[ytdl_hook]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\YoutubeDL.py", line 569, in __exit__
[ytdl_hook]   File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpupik7c6w\build\youtube_dl\utils.py", line 2775, in save
[ytdl_hook] FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Apps\\mpv\\cookies\\www.youtube.com.txt'
[ytdl_hook] youtube-dl failed: unexpected error occurred
Failed to recognize file format.

Exiting... (Errors when loading file)
Error: Downloader or player exited with error or termination signal

**Comment by Neomanbeta** [comment]
> And one more question: What the version of your youtube-dl? 还有一个问题，你们用的 youtube-dl 是什么版本？
> 
> `youtube-dl 2021.12.17` or `yt-dlp 2022.04.08`?

每次都是mpv updater.bat自己更新的，去文件夹里查看了一下是youtube-dl 2021.12.17

**Comment by Neomanbeta** [comment]
看来我暂时解决了这个问题。
我模糊的记得问题大概出现在我用updater.bat更新了版本之后，所以我就去sourceforge的下载页面往回挨个回退mpv的版本。
一直退到7天之前的版本[mpv-x86_64-20220227-git-b1fb4b7.7z](https://sourceforge.net/projects/mpv-player-windows/files/64bit/mpv-x86_64-20220227-git-b1fb4b7.7z/download)
这才正常了，问题算是暂时解决。再比这个新的版本，全部报一样的错误，原因不明。

**Comment by akiirui** [comment]
@Neomanbeta 你 play-with-mpv 脚本里启用了 `Try Pass Cookies`?
这个报错是没有找到 cookies 文件造成的，之前版本 youtube-dl 会在找不到这个文件的时候忽略它，看样子 2021.12.17 改了机制。

如果没有 cookies 文件就先不要启用 `Try Pass Cookies` 选项。

**Comment by akiirui** [comment]
我测试了一下，最新的 mpv 配合 youtube-dl 和 yt-dlp 在没有 cookies 文件的情况下都会报这个错误。
我在 mpv-handler 处理一下吧，如果启用了 `Try Pass Cookies` 但是又没有对应的 cookies 文件时，命令行输出 err，然后忽略 cookies 选项继续执行。
一会儿就改一下

**Comment by Neomanbeta** [comment]
我的确启动了Try Pass Cookies，之前我虽然没有需要用到这个地方，但是发现开了也不影响，就一直没关过。

**Comment by akiirui** [comment]
0.2.16 版本应该在启用 Try pass cookies 的情况下无法找到对应的 cookies 文件时会忽略选项并且提示一下，然后继续执行后续的播放了。

**Comment by Neomanbeta** [comment]
虽然我已经关了Try pass cookies了，但是我还是去更新一下handler，谢谢。

**Comment by Neomanbeta** [comment]
> 0.2.16 版本应该在启用 Try pass cookies 的情况下无法找到对应的 cookies 文件时会忽略选项并且提示一下，然后继续执行后续的播放了。

更新了最新版的handler，如果Try pass cookies选YES，那么工作是正常的，现在的问题是如果选No，还是报这个错误，这是更新的时候忘记处理了么？

**Comment by akiirui** [comment]
> > 0.2.16 版本应该在启用 Try pass cookies 的情况下无法找到对应的 cookies 文件时会忽略选项并且提示一下，然后继续执行后续的播放了。
> 
> 更新了最新版的handler，如果Try pass cookies选YES，那么工作是正常的，现在的问题是如果选No，还是报这个错误，这是更新的时候忘记处理了么？如果选No去播放，不是应该正常播放，不报错的么？

欸？选No播放的时候的报错信息可以贴一下么。油猴脚本那边选No了生成的链接应该是没有 `cookies=domain.com.txt` 这一段的呀。

**Comment by Neomanbeta** [comment]
我先重启一下电脑，再测试两次，别是因为我自己的原因造成的。

**Comment by Neomanbeta** [comment]
ok，简单测试了一下。
先说一下，报的错误还是我标题里的那个错误信息，没有别的。
重启电脑前，YouTube测试3次，发生一次。
重启电脑后，YouTube测试7次，发生一次，Bilibili测试7次，都正常。
Twitch没测试。
感觉好奇怪，让别人也测试一下吧，感觉这个发生几率挺低的，我也没法每次都复现。难道是我网络的问题么。。。

**Comment by akiirui** [comment]
> 

额，你像之前那样把 custom.toml 里的 mpv.exe 改为 mpv.com 才能看到完整的报错信息（

**Comment by Neomanbeta** [comment]
又坐在那反复开启关闭了几次，复现出来一次。报错信息如下：

Playing: https://www.youtube.com/watch?v=E6uP1Op97Ts&t=1s
[ffmpeg] https: HTTP error 403 Forbidden
Failed to open https://rr5---sn-ab02a0nfpgxapox-bh2zs.googlevideo.com/videoplayback?expire=1650224013&ei=LRdcYvGNGt222roPvae36Ag&ip=140.238.0.217&id=o-AGd2mWhRbv37Xf4lYeD8LMKUKXTx8Mkyzsg2M2CImo3c&itag=134&aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C278%2C298%2C299%2C302%2C303%2C308&source=youtube&requiressl=yes&mh=_P&mm=31%2C26&mn=sn-ab02a0nfpgxapox-bh2zs%2Csn-npoeen7k&ms=au%2Conr&mv=u&mvi=5&pl=25&spc=4ocVC3EOMxrlKmgtd4cPFgVv8OL-&vprv=1&mime=video%2Fmp4&ns=XqwHHgodfETO3aQvCPY-OxYG&gir=yes&clen=10575201&dur=315.866&lmt=1650164542096267&mt=1650201421&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=6319224&n=75cLRTAk7EwQKwYJDBC&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cspc%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgQ9hmMbhG2pYU_OSuLrDkNQZbFtdOYuh-RpXvc-QeJnICIQDSEBUcYicxg6i6N9VjvmaNAxsXDUYRdQMSsT_ccjWytQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl&lsig=AG3C_xAwRQIgQvKDdQO9EXOZgW4aJC8sVaM7f4vPJ-am78s9v70uuysCIQCSEJWmDmfx-IU3io1_lglZEAFelBDZjkAbxWEKrqSBlQ%3D%3D.
EDL: Could not open source file 'https://rr5---sn-ab02a0nfpgxapox-bh2zs.googlevideo.com/videoplayback?expire=1650224013&ei=LRdcYvGNGt222roPvae36Ag&ip=140.238.0.217&id=o-AGd2mWhRbv37Xf4lYeD8LMKUKXTx8Mkyzsg2M2CImo3c&itag=134&aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C278%2C298%2C299%2C302%2C303%2C308&source=youtube&requiressl=yes&mh=_P&mm=31%2C26&mn=sn-ab02a0nfpgxapox-bh2zs%2Csn-npoeen7k&ms=au%2Conr&mv=u&mvi=5&pl=25&spc=4ocVC3EOMxrlKmgtd4cPFgVv8OL-&vprv=1&mime=video%2Fmp4&ns=XqwHHgodfETO3aQvCPY-OxYG&gir=yes&clen=10575201&dur=315.866&lmt=1650164542096267&mt=1650201421&fvip=3&keepalive=yes&fexp=24001373%2C24007246&c=WEB&txp=6319224&n=75cLRTAk7EwQKwYJDBC&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cspc%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIgQ9hmMbhG2pYU_OSuLrDkNQZbFtdOYuh-RpXvc-QeJnICIQDSEBUcYicxg6i6N9VjvmaNAxsXDUYRdQMSsT_ccjWytQ%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl&lsig=AG3C_xAwRQIgQvKDdQO9EXOZgW4aJC8sVaM7f4vPJ-am78s9v70uuysCIQCSEJWmDmfx-IU3io1_lglZEAFelBDZjkAbxWEKrqSBlQ%3D%3D'.
No video or audio streams selected.

Exiting... (Errors when loading file)
Error: Downloader or player exited with error or termination signal

**Comment by akiirui** [comment]
这个就是上游或者是你本地网络问题了，HTTP error 403。

```
[ffmpeg] https: HTTP error 403 Forbidden
```

你可以尝试删除 youtube-dl.exe 运行 updater.bat，提示你需要 youtube-dl 还是 yt-dlp 的时候选 yt-dlp。

youtube-dl 很久没更新了，可能视频链接解析有点问题。如果 yt-dlp 还是有报 HTTP 403 的话，那就是你本地网络问题了。

**Comment by Neomanbeta** [comment]
好的，那我就清楚了，多谢帮忙。

**Comment by akiirui** [comment]
看来我得去 README 里提示 Windows 用户 `custom.toml` 里 mpv 执行文件写 `mpv.com`。

`mpv.exe` 这个不输出命令行信息的，所以通过 mpv-handler 调用的时候看不到是哪儿出错了。

**Comment by shmilee** [comment]
同遇到以下问题。
```  
  Failed to recognize file format.
  Exiting... (Errors when loading file)
```
但 `mpv --ytdl URL` 正常。
最终找到原因是 mpv 配置 .config/mpv/mpv.conf 里，我添加的 no-ytdl 选项。
猜测 mpv-handler 调 mpv 时没强制加 --ytdl  选项。

另外，AUR上的包是作者自己维护的吧，希望可以加个 -bin 包，这样就不用rust编译了（我测试用的是自己打包的bin，之前用过 cargo，下载加速换源，.cargo/ 体积占用，如果不是rust项目需求比较大，这些还挺不方便的）。

以上，只是一些建议。所以没开新issue，只是借一个相关issue提在这里。

**Comment by Neomanbeta** [comment]
一大早看到邮箱里两封被挖坟的邮件的我表示：满头问号？？？
