### ISSUE TITLE
Userscript detects mpv-handler.exe, and it does not run the player

### ISSUE THREAD

**Issue by kazumi513** [akiirui/mpv-handler#24]
Userscript检测mpv处理程序。exe，并且一旦你点击"用mpv-handler打开。exe"，它确实加载了带有"播放：[视频的链接]"字样的命令提示符，但是当我手动点击它加载它时，mpv播放器不会加载，甚至不会播放视频:

<p align="center">
<img src="https://i.imgur.com/hNFORKW.png"style="width:20%; border:0;">
</p>

然后当我点击"打开mpv-handler。exe"，它打开这个命令提示符，仅此而已。 Mpv播放器不加载，命令提示符是程序将去的最远。

<p align="center">
<img src="https://i.imgur.com/e4KHc8R.png"style="width:20%; border:0;">
</p>

当我等待几分钟时，我最终得到这个错误:

![mpv-handler_RkOamPI8xN](https://user-images.githubusercontent.com/101737464/163685039-0a0bd0b8-11b3-47f7-8807-befec8e05d4d.png)

我只想让视频在播放器中运行。 再次谢谢。

**Comment by akiirui** [comment]
Duplicate #23
