### ISSUE TITLE
Path support for youtube-dl/yt-dlp (Windows)

### ISSUE THREAD

**Issue by ZXSwire3** [akiirui/mpv-handler#25]
I'm not really sure if this is something that you would have to support or if it would be the mpv devs, but I think it would be helpful to at least put it in the [README.md](https://github.com/akiirui/mpv-handler#readme) that you have to put the youtube-dl/yt-dlp executable in the same folder as mpv. I kept getting errors saying 
>Playing: https://www.youtube.com/watch?v=dQw4w9WgXcQ
[ytdl_hook]
[ytdl_hook] youtube-dl failed: not found or not enough permissions
Failed to recognize file format.

>Exiting... (Errors when loading file)
Error: Downloader or player exited with error or termination signal

but I couldn't figure out why because I had already put both youtube-dl and yt-dlp in my `PATH`. It took me a while to realize that I had to put it in the same folder that I had my mpv executable. It would be nice if it was just supported that it would check if youtube-dl/yt-dlp are in the `PATH` so that it doesn't have to put in a specific place.

**Comment by leekool** [comment]
on both my linux and windows setups i don't have the yt-dlp executable in my mpv follder and don't face this issue

**Comment by akiirui** [comment]
By default, mpv-handler use mpv ytdl-hook to get the video.

So, if your mpv cannot found youtube-dl binary file (if it isn't set in `PATH`), check https://mpv.io/manual/stable/#options-ytdl-path.

That is provide by mpv, so im not add any option for mpv-handler.

**Comment by akiirui** [comment]
> but I couldn't figure out why because I had already put both youtube-dl and yt-dlp in my PATH.

And i try move `yt-dlp.exe` to other place and add this path to environment variable `PATH`, it works fine.

Can i see the value of your environment variable PATH?
