### ISSUE TITLE
无法使用 求教

### ISSUE THREAD

**Issue by kimberlytor** [akiirui/mpv-handler#26]
mpv, mpv-handler和油猴脚本均是最新版，但是视频无法播放，提示[ffmpeg] https: HTTP error 403 Forbidden
请教下是因为什么原因呢？
![mpv-handler版本检查](https://user-images.githubusercontent.com/100819379/169015298-d4b47084-1318-4cad-bb03-b76dd46015de.png)
![mpv版本检查](https://user-images.githubusercontent.com/100819379/169015331-871e0151-2126-4ae2-8fef-c4381d1f9704.png)
![mpv-handler报错信息](https://user-images.githubusercontent.com/100819379/169015356-b07f7bae-0052-4be0-8043-8b43f4adb1c2.png)

**Comment by akiirui** [comment]
目前 mpv + yt-dlp 播放 bilibili 视频时有问题，详情参见上游 https://github.com/mpv-player/mpv/issues/9978

我这里有一个临时解决方案：

```ini
http-header-fields-add="Referer: https://www.bilibili.com"
```

添加以上内容到 mpv.conf 里，就可以正常播放bilibili视频了。~~但是有可能会导致其他站点的视频播放出现问题~~

**Comment by akiirui** [comment]
MPV 上游已经修复了相关问题 https://github.com/mpv-player/mpv/commit/431473310f9d86f6ae030ce3432897edebe5ab89

Linux 可以自行构建，Windows 用户可以等待 https://sourceforge.net/projects/mpv-player-windows/files 更新
