### ISSUE TITLE
Can't find yt-dlp after uninstalling youtube-dl

### ISSUE THREAD

**Issue by Antiwhore** [akiirui/mpv-handler#31]
Hello!
I've installed the script along with youtube-dl, but the performance was crappy, so I uninstalled youtube-dl and installed yt-dlp instead. After that the script started saying "[ytdl_hook] youtube-dl failed: not found or not enough permissions". Then I've written yt's location into config, restarted the browser, but it didn't help.

**Comment by akiirui** [comment]
what version of mpv-handler are you using? OS?

**Comment by akiirui** [comment]
> [ytdl_hook] youtube-dl failed: not found or not enough permissions

It looks like mpv doesn't find yt-dlp. Is yt-dlp binary in the same directory as mpv?

And check your mpv version, recommend to upgrade to latest.

**Comment by Antiwhore** [comment]
This is the latest version (as of today) on Debian-based Linux.
Obviously it doesn't find yt-dlp. mpv is in /usr/bin and yt-dlp is in ~/.local/bin.
mpv version is 0.32.0, which is older than that commit.

**Comment by akiirui** [comment]
Okay, maybe you can edit mpv.conf:
```
script-opts=ytdl_hook-ytdl_path=PATH-TO-YT-DLP.
```

**Comment by Antiwhore** [comment]
I've just installed the newest mpv, but via flatpak (there's just old version in the repo). It says it can't find the player. How do I make it discover mpv from flatpak?

**Comment by Antiwhore** [comment]
Tried to edit the conf in the old version as well. Says "[ytdl_hook] script-opts: unknown key ytdl_path, ignoring"

**Comment by Antiwhore** [comment]
I've installed the newest version from a deb package and it's finally working. Now I have another question, which I'll ask in another issue.
