### ISSUE TITLE
Add user-agent support to the Parameters (Optional)

### ISSUE THREAD

**Issue by nanoia** [akiirui/mpv-handler#35]
Some websites like '*.baidupcs.com' set anti hotlinking and verify user-agent, please add this parameter to optional parameters.

**Comment by akiirui** [comment]
I don't know what user-agent is accepted by these sites.
But you can use profiles feature to set different `user-agent` and `http-header-fields` for special site:

mpv.conf:
```
Some options...

[baidupcs]
user-agent=MPV
http-header-fields='Field1: value1','Field2: value2'
```

userscript:
`MPV Profile`: `default` > `baidupcs`

But userscript doesn't support save per-site profile currently (may be implemented asap)

**Comment by nanoia** [comment]
> I don't know what user-agent is accepted by these sites. But you can use [profiles feature](https://mpv.io/manual/master/#profiles) to set different `user-agent` and `http-header-fields` for each site:
> 
> mpv.conf:
> 
> ```
> ...
> 
> [baidupcs]
> user-agent=mpv
> http-header-fields='Field1: value1','Field2: value2'
> ```
> 
> userscript:
> 
> `MPV Profile`: `default` > `baidupcs`
> 
> But userscript doesn't support saving profiles by site currently (may be implemented asap)

Thanks for your reply, i originally expected to call mpv-handler in some websites via `mpv://play/<base64>/?user-agent=pan.baidu.com`, but  i find config by profile is a better flexible solution according to your prompt. This issue may probably be closed. Have a good day!
