### ISSUE TITLE
Can't run bat script

### ISSUE THREAD

**Issue by DHYTFG** [akiirui/mpv-handler#37]
bat script in Windows 10 writes that it is not running with administrator rights, although this is not true. I do the following to run as admin:
1. right click on the bat file
2. click on "Run as administrator"

**Comment by akiirui** [comment]
That script is working for me on Windows 7/10/11.

Try to run `openfiles >nul` in cmd.exe with admin privileges and paste the outputs for me, thanks.

**Comment by akiirui** [comment]
No reply for long time, Closed.
