### ISSUE TITLE
Where's the config file located?

### ISSUE THREAD

**Issue by CHJ85** [akiirui/mpv-handler#38]
I installed mpv-handler through the AUR. I Need to change the yt-dlp location as I installed it through pip.
So, where's the config file located?

**Comment by akiirui** [comment]
Create $HOME/.config/mpv-handler/config.toml and edit it (if needed)

**Comment by akiirui** [comment]
But why are you using pip to install yt-dlp?  It's already in the official repository.

**Comment by CHJ85** [comment]
Thanks. I figured it out.
