### ISSUE TITLE
How can Use it In AARCH64 Linux!

### ISSUE THREAD

**Issue by sallyhaj** [akiirui/mpv-handler#40]
Hello,
Thank you first for the app.
I am using Raspberry Pi with Linux.
How can I use your tool in my device? Or if there is a way to compile it, please help me with that.
Regards,

**Comment by akiirui** [comment]
May I ask what Linux distribution you are using?

1. if your distribution official repository has rust package, install it. if not, follow https://www.rust-lang.org/tools/install guide.
2. Clone this repository
3. `cd` and `cargo build`
4. Follow [README#Manual-installation](https://github.com/akiirui/mpv-handler#manual-installation)

**Comment by sallyhaj** [comment]
I use Debian and Fedora.
Okay, thank you @akiirui
