### ISSUE TITLE
Windows平台无法使用，只闪了一下CMD

### ISSUE THREAD

**Issue by weakmusic** [akiirui/mpv-handler#41]
MPV、Handler、ytdl均在环境变量内，如下
youtube-dl
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options.

mpv-handler
mpv-handler 0.3.4

Usage:
  mpv-handler [options] <url>

OPTIONS:
  -v, --version    show version

mpv -v
[cplayer] Command line options: '-v'
[cplayer] mpv 0.35.0-486-g0bfafd24 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects

ffmpeg -v
ffmpeg version 6.0-essentials_build-www.gyan.dev Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12.2.0 (Rev10, Built by MSYS2 project)

config.toml如下
# mpv = "D:/Program Files/MPV_lazy/mpv-lazy/mpv.com"

# ytdl = "D:/Program Files/mpv-handler-windows-amd64/youtube-dl.exe"

网页权限已开  点击左下角的图标后CMD会闪一下 但是没有拉起MPV

这些软件 一定要用ReadMe里的版本才能用吗？

**Comment by akiirui** [comment]
在 `mpv-handler.exe` 的目录中右键”在此处打开命令行“，然后运行 
```
.\mpv-handler.exe mpv://play/aHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g_dj1HZ2tuMmY1ZS1JVQ/
```
并贴出输出的内容，谢谢。

**Comment by weakmusic** [comment]
PS D:\Program Files\mpv-handler-windows-amd64> .\mpv-handler.exe mpv://play/aHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g_dj1HZ2tuMmY1ZS1JVQ/
Playing: https://www.youtube.com/watch?v=Ggkn2f5e-IU


但是MPV还是没有被拉起

**Comment by akiirui** [comment]
单独看这个输出配置是没有问题的，mpv 不出来可能是代理问题。你之前测试的时候是测试的哪一个网站？BiliBili找一个视频看看？

**Comment by weakmusic** [comment]
后面还有返回的内容 但是我代理已经是全局模式了 不应该是代理的问题了

Playing: https://www.youtube.com/watch?v=Ggkn2f5e-IU
[ffmpeg] tcp: Connection to tcp://www.youtube.com:443 failed: Error number -138 occurred
Failed to open https://www.youtube.com/watch?v=Ggkn2f5e-IU.


是在bilibili试的 但是就是CMD闪一下就没了 无事发生

**Comment by akiirui** [comment]
bilibili 闪一下无事发生？我随便找了个视频，试试:
```
mpv-handler mpv://play/aHR0cHM6Ly93d3cuYmlsaWJpbGkuY29tL3ZpZGVvL0JWMVZ1NHkxdjdDRi8/
```

**Comment by weakmusic** [comment]
[ffmpeg] https: inflate return value: -3, incorrect header check

返回的这个

**Comment by akiirui** [comment]
我认为是你的 ffempg 有问题，直接使用 
```
mpv.com https://www.bilibili.com/video/BV1Vu4y1v7CF/
``` 
应该也会报同样的错误。
建议更新一下你当前使用的mpv+ffmpeg或者更换其他维护者的版本。

然后上面 

> Playing: https://www.youtube.com/watch?v=Ggkn2f5e-IU
> [ffmpeg] tcp: Connection to tcp://www.youtube.com:443 failed: Error number -138 occurred
> Failed to open https://www.youtube.com/watch?v=Ggkn2f5e-IU.

这很明显是由于代理问题导致的无法播放，不知道你全局代理是怎么配置的，但是 ffmpeg 并没有走代理。

**Comment by weakmusic** [comment]
非常感谢解答！ 我去更换一个ffmpeg试一下。

**Comment by akiirui** [comment]
> 非常感谢解答！ 我去更换一个ffmpeg试一下。

更换后有解决 
> [ffmpeg] https: inflate return value: -3, incorrect header check
的问题吗？

**Comment by weakmusic** [comment]
用命令行可以播mpv-handler mpv://play/aHR0cHM6Ly93d3cuYmlsaWJpbGkuY29tL3ZpZGVvL0JWMVZ1NHkxdjdDRi8/了


但是从网页点左下角的按钮还是不行 复制按钮上的链接 使用命令行也能播

**Comment by weakmusic** [comment]
搞定了 
重新install 了一下 mpv-handler 就行了 因为我发现按钮打开的不是mpv-handler.exe而是mpv-handler link


非常感谢

**Comment by weakmusic** [comment]
主要还是MPV和FFMPEG的版本问题 
安装
https://greasyfork.org/zh-CN/scripts/416271-play-with-mpv
这里面的MPV就可以了

非常感谢
