### ISSUE TITLE
现在好像不怎么好用啊。接口错误

### ISSUE THREAD

**Issue by HelSing-M** [akiirui/mpv-handler#44]
Incorrect protocol

**Comment by HelSing-M** [comment]
Both are latest version.I want to use this script--- 
https://greasyfork.org/zh-CN/scripts/474231-115%E4%B8%8D%E5%A4%A7%E5%8A%A9%E6%89%8B-full?locale_override=1

**Comment by akiirui** [comment]
Please contact the author of that user script.
This script doesn't use mpv-handler correctly.

![](https://github.com/akiirui/mpv-handler/blob/main/share/proto.png)
