### ISSUE TITLE
Hello friends! Custom command line program path configuration should be provided.

### ISSUE THREAD

**Issue by zhouxinghong** [akiirui/mpv-handler#46]
Hello friends! Custom command line program path configuration should be provided.

For example, I want to replace the default cmd with "D:xxxxx/PowerShell.exe"

Thank you very much for such an excellent extension. 👍🎉😜🍦

**Comment by zhouxinghong** [comment]
```
mpv = "/usr/bin/mpv"

# Optional, Type: String
# The path of mpv binary
# Default value:
# - Linux: mpv
# - Windows: mpv.com

ytdl = "/usr/bin/yt-dlp"

# Optional, Type: String
# The path of yt-dlp binary
# Default value:
# - Linux: yt-dlp
# - Windows: yt-dlp.exe

proxy = "http://example.com:8080"

# Optional, Type: String
# The proxy server address

# For Windows users:
#   The path can be "C:\\folder\\some.exe" or "C:/folder/some.exe"
Output="D:/xxxxx/PowerShell.exe"
```

**Comment by akiirui** [comment]
mpv-handler doesn't execute any "command lineprograms" you says, such as `cmd.exe` or `powershell.exe`.

The console windows is provided by mpv-handler itself.

**Comment by zhouxinghong** [comment]
It would be better if users were allowed to customize the output program!
For example, I want to replace the default cmd with "D:/xxxxx/PowerShell.exe"

**Comment by akiirui** [comment]
Is there any special purpose for using PowerShell to output?

**Comment by zhouxinghong** [comment]
Similar to Linux system command environment

**Comment by zhouxinghong** [comment]
We rarely use the Windows 10 default cmd program.

**Comment by akiirui** [comment]
I just said that the console window of mpv-handler isn't `cmd.exe`.

**Comment by zhouxinghong** [comment]
Please allow users to configure their familiar command line programs.

**Comment by akiirui** [comment]
I'm not quite sure why you insist on running mpv-handler in a **command line program**, I wouldn't add this feature without a clear purpose.

For special purposes, you can add `"powershell" "-Command"` to `HKCR\mpv\shell\open\command` to the header of its value by Windows Registry Editor.

Example, from:
```
"C:\Programs\mpv-handler\mpv-handler.exe" "%1"
```
To
```
"powershell.exe" "-Command" "C:\Programs\mpv-handler\mpv-handler.exe" "%1"
```

**Comment by zhouxinghong** [comment]
Because we often use mpv --xxxx -- no-config http://xxxxxxx in the command line to play videos or test configurations.

Not only will we be using powershell but in some cases third party command line client programs. Adding this function will be more convenient for certain situations where command line operations must be used.

**Comment by akiirui** [comment]
Yes, I know we usually execute `mpv` in console to test configurations, but does this have anything to do with mpv-handler?

The mpv-handler uses hardcoded parameter templates, such as:

https://github.com/akiirui/mpv-handler/blob/efd86a80bb32ff81adb0b1bb433a4b40e2df0591/src/plugins/play.rs#L125-L148

And no other parameters are provided except `-v | --version`:

https://github.com/akiirui/mpv-handler/blob/efd86a80bb32ff81adb0b1bb433a4b40e2df0591/src/main.rs#L29-L39

If you open mpv-handler by browser userscript (e.g. play with mpv), It  actually is execute `mpv-handler mpv://play/<ENCODED_URL>`. And you cannot edit the parameter at this time.

Even you run these command in powershell or other shells, it doesn't change anything. 

mpv-handler parses the URL, calls mpv, and exits successfully on exit or end of video. Or outputs an error message and exits when it encounters an error.

**If you need to configure mpv, open the shell you want and do what you want.**

**Comment by zhouxinghong** [comment]
If this function is difficult to implement, can users be allowed to hide the pop-up command line window and only pop up the mpv player.

**Comment by zhouxinghong** [comment]
Found an issue that needs improvement:
After successfully calling mpv to take over the browser to play the video, you should pause or stop playing the video in the browser.

**Comment by akiirui** [comment]
> Found an issue that needs improvement: After successfully calling mpv to take over the browser to play the video, you should pause or stop playing the video in the browser.

Normally, the video from the webpage is paused when the play button of the userscript is clicked.

https://github.com/akiirui/userscript/blob/6fc9440aedc3b97f52c55df1c3f780ac8e351737/userscript.js#L343-L347

**Comment by zhouxinghong** [comment]
![image](https://github.com/akiirui/mpv-handler/assets/54253524/6e2906c8-3fd3-4579-ba1c-3581f14de17f)
I just tried this and found that after the script successfully calls the mpv player, YouTube in the browser continues...

**Comment by zhouxinghong** [comment]
I just tried this and found that after the script successfully calls the mpv player, YouTube in the browser continues...
![image](https://github.com/akiirui/mpv-handler/assets/54253524/fcc9d899-8a31-4389-ae45-7a3a039002dd)

**Comment by zhouxinghong** [comment]
![image](https://github.com/akiirui/mpv-handler/assets/54253524/ef0559d9-4fb8-42d8-8526-aba9a64e4f67)
Cannot hide command line window
0.3.6
Windows 10
Chrome 123

**Comment by akiirui** [comment]
Try v0.3.7 and userscript 2024.04.22.2. Don't forget run `handler-install.bat` once more.

**Comment by akiirui** [comment]
Done, https://github.com/akiirui/mpv-handler/releases/tag/v0.3.7
