### ISSUE TITLE
when setting 'quality=360p&v_codec=h264', only v_codec takes effect

### ISSUE THREAD

**Issue by shmilee** [akiirui/mpv-handler#49]
## DEBUG info

1. default, `Video --vid=1 (*) (hevc 852x480 30.000fps)`, `["format-sort"]` is `nil`
```shell
[$] mpv-handler 'mpv-debug://play/aHR0cHM6Ly93d3cuYmlsaWJpbGkuY29tL3ZpZGVvL0JWMVZENDIxdTdHby8_dmRfc291cmNlPTE5Nm
FkMTA2NGVjMGM1NWRjYjI0OTJlMWRjNmYxYzVj/?cookies=www.bilibili.com.txt'
Playing: https://www.bilibili.com/video/BV1VD421u7Go/?vd_source=196ad1064ec0c55dcb2492e1dc6f1c5c

[test_properties_hook] -> 99, i=10, type(ytdl-raw-options)=table, {
[test_properties_hook]   cookies = "/home/shmilee/.config/mpv-handler/cookies/www.bilibili.com.txt",
[test_properties_hook]   <metatable> = {
[test_properties_hook]     info = "native map",
[test_properties_hook]     type = "MAP"
[test_properties_hook]   }
[test_properties_hook] }
[test_properties_hook] -> 99, i=11, type(ytdl-raw-options-append)=nil, nil

 (+) Video --vid=1 (*) (hevc 852x480 30.000fps)
 (+) Audio --aid=1 (*) (aac 2ch 44100Hz)
     Subs  --sid=1 --slang=danmaku 'xml' (null) (external)
```

2. only set `quality`,  ` ["format-sort"] = "res:360"`, then `Video --vid=1 (*) (hevc 640x360 30.000fps)`
```shell
[$] mpv-handler 'mpv-debug://play/aHR0cHM6Ly93d3cuYmlsaWJpbGkuY29tL3ZpZGVvL0JWMVZENDIxdTdHby8_dmRfc291cmNlPTE5Nm
FkMTA2NGVjMGM1NWRjYjI0OTJlMWRjNmYxYzVj/?cookies=www.bilibili.com.txt&quality=360p'
[test_properties_hook] -> 99, i=10, type(ytdl-raw-options)=table, {
[test_properties_hook]   cookies = "/home/shmilee/.config/mpv-handler/cookies/www.bilibili.com.txt",
[test_properties_hook]   ["format-sort"] = "res:360",
[test_properties_hook]   <metatable> = {
[test_properties_hook]     info = "native map",
[test_properties_hook]     type = "MAP"
[test_properties_hook]   }
[test_properties_hook] }

 (+) Video --vid=1 (*) (hevc 640x360 30.000fps)
 (+) Audio --aid=1 (*) (aac 2ch 44100Hz)
     Subs  --sid=1 --slang=danmaku 'xml' (null) (external)
```

3. set both, ["format-sort"] = "+vcodec:h264"`, then ``Video --vid=1 (*) (h264 852x480 30.000fps)`
```shell
[$] mpv-handler 'mpv-debug://play/aHR0cHM6Ly93d3cuYmlsaWJpbGkuY29tL3ZpZGVvL0JWMVZENDIxdTdHby8_dmRfc291cmNlPTE5Nm
FkMTA2NGVjMGM1NWRjYjI0OTJlMWRjNmYxYzVj/?cookies=www.bilibili.com.txt&quality=360p&v_codec=h264'
[test_properties_hook] -> 6, i=10, type(ytdl-raw-options)=table, {
[test_properties_hook]   cookies = "/home/shmilee/.config/mpv-handler/cookies/www.bilibili.com.txt",
[test_properties_hook]   ["format-sort"] = "+vcodec:h264",
[test_properties_hook]   <metatable> = {
[test_properties_hook]     info = "native map",
[test_properties_hook]     type = "MAP"
[test_properties_hook]   }
[test_properties_hook] }

 (+) Video --vid=1 (*) (h264 852x480 30.000fps)
 (+) Audio --aid=1 (*) (aac 2ch 44100Hz)
     Subs  --sid=1 --slang=danmaku 'xml' (null) (external)
```

## how to fix
It seems that the conflict between the two parameters occurred because they both take effect through setting `format-sort`  to ytdl.
https://github.com/akiirui/mpv-handler/blob/5672c8931c48dedc4d42ec0d1bfa2faca3388814/src/plugins/play.rs#L7
https://github.com/akiirui/mpv-handler/blob/5672c8931c48dedc4d42ec0d1bfa2faca3388814/src/plugins/play.rs#L140-L148

If we use "--ytdl-raw-options-append=format-sort=res:360 --ytdl-raw-options-append=format-sort=+vcodec:h264", we will only get `["format-sort"] = "+vcodec:h264"`.
The correct way is to setting  "--ytdl-raw-options-append=format-sort=res:360,+vcodec:h264", then we can get the expected  output:
```
[mpv_url_scheme] setting table ytdl-raw-options={"cookies" = "/home/shmilee/.config/mpv-handler/cookies/www.bilibili.com.txt", 
"format-sort" = "res:360,+vcodec:h264"}

[test_properties_hook] -> 99, i=10, type(ytdl-raw-options)=table, {
[test_properties_hook]   cookies = "/home/shmilee/.config/mpv-handler/cookies/www.bilibili.com.txt",
[test_properties_hook]   ["format-sort"] = "res:360,+vcodec:h264",
[test_properties_hook]   <metatable> = {
[test_properties_hook]     info = "native map",
[test_properties_hook]     type = "MAP"
[test_properties_hook]   }
[test_properties_hook] }

 (+) Video --vid=1 (*) (h264 640x360 30.000fps)
 (+) Audio --aid=1 (*) (aac 2ch 44100Hz)
     Subs  --sid=1 --slang=danmaku 'xml' (null) (external)
```

By the way, after using [mpv lua-scripting](https://mpv.io/manual/master/#lua-scripting) to show the debug information,
I find that it is possible to make a protocol handler for `mpv://base64-url/?p=1&k=v` by mpv lua script (name?mpv_url_scheme.lua?).

**Comment by akiirui** [comment]
Thanks for report! It is fixed in https://github.com/akiirui/mpv-handler/commit/d17c52d14bc3b3b3fc38eafc31040cdd991fd158.

> I find that it is possible to make a protocol handler for mpv://base64-url/?p=1&k=v by mpv lua script (name?mpv_url_scheme.lua?).

Emm, maybe it's another better method to do this, I'll go take a look when I have time, thank you.

**Comment by akiirui** [comment]
Maybe like this one, https://github.com/Digitalone1/mpv-acestream/blob/master/scripts/mpv-acestream.lua

But if we use Lua script method, we will lose some features. like console outputs and this chromium fix
https://github.com/akiirui/mpv-handler/blob/main/src/plugins/play.rs#L42-L46

**Comment by shmilee** [comment]
Yes, like `mpv-acestream.lua`, what we need to do is just to add a hook to handle `mpv://` before `ytdl_hook`.  (check manual of `mp.add_hook`, `set_property`, etc.)
I am trying to write an mpv script. After testing, it has been verified that handling the mpv:// protocol with a
 script is achievable. 
https://github.com/shmilee/scripts/blob/6220c532f6e5102bfceed252831cd93c0447620c/mpv/scripts/mpv_url_scheme.lua

* [x] console outputs.  related to .desktop `Terminal=true`?
```
[$] cat /usr/share/applications/mpv-handler-debug.desktop                 :) 0
[Desktop Entry]
Type=Application
Name=mpv-handler-debug
GenericName=Multimedia player
Comment=Play website videos and songs with mpv & yt-dlp (Debug)
NoDisplay=true
Icon=mpv
Exec=mpv -- %U
Terminal=true
Categories=AudioVideo;Audio;Video;Player;TV;
MimeType=x-scheme-handler/mpv-debug;
X-KDE-Protocols=mpv-debug
```
```
[mpv_url_scheme] Using play-base64 to handle mpv-debug://play/aHR0cHM6Ly93d3cuYmlsaWJpbGkuY29tL3ZpZGVvL0JWMVZENDIxdTdHby8_dmRfc291cmNlPTE5NmFkMTA2NGVjM
GM1NWRjYjI0OTJlMWRjNmYxYzVj/?cookies=www.bilibili.com.txt&quality=360p&v_codec=h264&profile=low-latency
[mpv_url_scheme] Applying profile: low-latency
[mpv_url_scheme] setting stream-open-filename="https://www.bilibili.com/video/BV1VD421u7Go/?vd_source=196ad1064ec0c55dcb2492e1dc6f1c5c"
[mpv_url_scheme] setting table ytdl-raw-options={"cookies" = "/home/shmilee/.config/mpv-handler/cookies/www.bilibili.com.txt",
 "format-sort" = "res:360,+vcodec:h264"}
```
* [x] register the protocol for mpv. Yes, may need a new `.desktop` file.
* [ ] LD_LIBRARY_PATH and chromium(not installed). not tested: set `Exec=env LD_LIBRARY_PATH='' mpv -- %U` in desktop file.

**Comment by akiirui** [comment]
Good works, I've never used lua, so I can't help you there. The lua version might be a more lightweight solution.

**Comment by akiirui** [comment]
> console outputs. related to .desktop Terminal=true

It is Linux only method, maybe we shoud find another method for Windows.

> LD_LIBRARY_PATH and chromium(not installed). not tested: set Exec=env LD_LIBRARY_PATH='' mpv -- %U in desktop file.

Maybe `Exec=env -u LD_LIBRARY_PATH mpv -- %U` is better?

**Comment by shmilee** [comment]
For console outputs, how about adding `--log-file=` option for mpv? Then we can debug with the log-file.

> Maybe Exec=env -u LD_LIBRARY_PATH mpv -- %U is better?

Yes, `-u` is better.

**Comment by akiirui** [comment]
> For console outputs, how about adding --log-file= option for mpv? Then we can debug with the log-file.

Maybe this is an option. It's also good to make it work first and then add more features later. Welcome your Lua version!
