### ISSUE TITLE
那個mpv和yt-dlp已經下載了爲什麼不能進

### ISSUE THREAD

**Issue by bayunquan** [akiirui/mpv-handler#50]
![IMG20240714225124](https://github.com/user-attachments/assets/bfd79e2b-de8f-4b89-9ed6-7bb8942781d0)

![IMG20240714225752](https://github.com/user-attachments/assets/62528d5f-8b5c-4fdb-b398-223a5f3431b7)

那個default value我改料很多次就算改回mpv.com還是沒有用

**Comment by bayunquan** [comment]
![IMG20240714225124](https://github.com/user-attachments/assets/2597fff4-6950-4608-9f08-09fa770a8443)

**Comment by bayunquan** [comment]
firefox顯示無法理解的網址

**Comment by akiirui** [comment]
是否有以管理員權限執行 handler-install.bat？

**Comment by bayunquan** [comment]
已經執行了但還是不能

**Comment by akiirui** [comment]
執行完後控制台視窗有顯示以下內容嗎？

```
Successfully installed mpv-handler
Enjoy!
Press any key to continue . . .
```

**Comment by bayunquan** [comment]
沒有

**Comment by bayunquan** [comment]
它直接跳掉

**Comment by bayunquan** [comment]
然後現在打個比如我的Ani-Cli看動漫的那個我之前下載過了但它說沒有此代碼

**Comment by bayunquan** [comment]
所以我覺得是windows的問題

**Comment by akiirui** [comment]
> 它直接跳掉

 handler-installl.bat 运行直接跳掉？不应该啊，不管成功与否都会输出信息并等待按键的。

**Comment by bayunquan** [comment]
沒事我自己修好了我把windows的system32加到PATH

**Comment by bayunquan** [comment]
但是奇怪好像加載不出來

**Comment by akiirui** [comment]
所以你到底做了哪些操作？

**Comment by bayunquan** [comment]
裝是裝到料但我的mpv遲遲載不出來

**Comment by bayunquan** [comment]
![IMG20240718001717](https://github.com/user-attachments/assets/7da81ea6-b6ff-416d-9ae0-7c363b1ddf98)

**Comment by bayunquan** [comment]
幫我看看我是不是那裏有改錯

**Comment by bayunquan** [comment]
![IMG20240718001905](https://github.com/user-attachments/assets/0a9a9517-2c60-48bf-a36e-10b0aa35859b)

**Comment by bayunquan** [comment]
冒味問一下mpv-lazy可以用嗎？

**Comment by bayunquan** [comment]
好像是連接不到電腦這邊

**Comment by bayunquan** [comment]
因爲如果我調run with console正常來講它會開命令提示字元

**Comment by bayunquan** [comment]
但這次他沒有

**Comment by bayunquan** [comment]
還是那個插件有問題

**Comment by akiirui** [comment]
配置文件里需要把自定义的数值那一行的 # 号去掉，默认是注释掉的不会应用。
按照我下面说的步骤操作试试，如果那一步出现问题就告诉我，有报错信息可以截图。

1. 从GitHub release page 下载最新的 mpv-handler Windows版。
2. 解压到你想要的目录。
3. 在这个目录中右键以管理员权限执行 handler-install.bat。
4. 修改 config.toml 自定义你需要修改的值（自定义值后删掉该行前面的 #
5. 浏览器安装 violentmoneky 或） tampermoneky 扩展。
6. 安装 Play With MPV 油猴脚本。
7. 在视频页面点击左下角脚本的设置按钮，把 run with console 设置为 yes 并保存。
8. 在视频页面点击左下角mpv图标播放。
9. 查看是否弹出命令行窗口并且输出信息。

**Comment by bayunquan** [comment]
console跑不出來

**Comment by akiirui** [comment]
> console跑不出來

前面的步骤都没问题？ Firefox也不提示无法识别的网址了？

**Comment by akiirui** [comment]
请贴出你的 config.toml 内容。
前面看到你有自行修改过PATH环境变量，也一并截图贴出。

**Comment by bayunquan** [comment]
> > console跑不出來
> 
> 前面的步骤都没问题？ Firefox也不提示无法理解的网址了？
是的

**Comment by bayunquan** [comment]
問題是它我點那個mpv圖標它在走着料但命令行窗口加載不出來

**Comment by bayunquan** [comment]
mpv也是

**Comment by bayunquan** [comment]
![IMG20240719004015](https://github.com/user-attachments/assets/1b1ae639-4f53-4fd9-9ea3-f7faa37a53f3)

**Comment by bayunquan** [comment]
![IMG20240719004056](https://github.com/user-attachments/assets/5f1571cc-9815-400e-91b0-ca2a75741eea)

**Comment by akiirui** [comment]
> ![IMG20240719004056](https://github.com/user-attachments/assets/5f1571cc-9815-400e-91b0-ca2a75741eea)
> 

你把 mpv.exe mpv.com ytdlp的那三行删了重启电脑试试（
不清楚怎么添加环境变量的话就最好不要动

**Comment by akiirui** [comment]
然后把play with mpv的设置也截图看一下

**Comment by bayunquan** [comment]
冒味問一下windows的環境變量

**Comment by bayunquan** [comment]
![IMG20240719194648](https://github.com/user-attachments/assets/f4b34dc0-46f0-4c8a-9091-cde8d74aded5)

**Comment by bayunquan** [comment]
https://github.com/user-attachments/assets/67168bfd-601e-4362-9bf6-c5b9374bb9e6

**Comment by bayunquan** [comment]
![IMG20240719201324](https://github.com/user-attachments/assets/4967227c-d07c-487e-826d-fe250d4c1385)

**Comment by akiirui** [comment]
config.toml 和 userscript 的配置都没问题了，环境变量按照上面的修改了的话也没问题。
让我再确认一下注册表是否由 handler-install.bat 配置正确。

Win+R 运行 regedit，浏览以下位置：
- `Computer\HKEY_CLASSES_ROOT\mpv\shell\open\command`
- `Computer\HKEY_CLASSES_ROOT\mpv-debug\shell\open\command`

贴出右侧的内容

**Comment by bayunquan** [comment]
看到mpv罷了

**Comment by bayunquan** [comment]
![IMG20240719221003](https://github.com/user-attachments/assets/d49d12a0-92a3-4343-82b6-76abe7eab9f2)

**Comment by bayunquan** [comment]
![IMG20240719221413](https://github.com/user-attachments/assets/57319f96-4b69-4491-af9a-7ccb23cfb9da)

**Comment by bayunquan** [comment]
本來好好的但不懂zomok出問題

**Comment by bayunquan** [comment]
它顯示沒有

**Comment by akiirui** [comment]
> 它顯示沒有

那就说明你的 handler-install.bat 并没有运行成功。
以管理员权限运行，成功后会输出
<img width="200" alt="Screenshot_2024-07-20_00-16-21" src="https://github.com/user-attachments/assets/950af7b8-5fc8-4f53-9c99-62247fb06eaf">

**Comment by bayunquan** [comment]
![IMG20240720010945](https://github.com/user-attachments/assets/8c7296c5-8298-461d-baa5-e2594ac3f380)
![IMG20240720011006](https://github.com/user-attachments/assets/95992bd2-56d0-480c-ae9c-c104afb62e8e)

**Comment by akiirui** [comment]
现在是成功写入注册表了吗，确认exe在这个位置的话，就尝试在浏览器中点击播放按钮。

**Comment by akiirui** [comment]
如果还是没任何反应的话，就在powershell里运行这个 mpv-handler.exe 看是否能够正常运行。

**Comment by bayunquan** [comment]
![IMG20240720084040](https://github.com/user-attachments/assets/7a034df5-9b01-4a2f-8352-ec8b22b24247)

**Comment by bayunquan** [comment]
好像沒有反應

**Comment by akiirui** [comment]
.\mpv-handler.exe

**Comment by bayunquan** [comment]
![IMG20240728165321](https://github.com/user-attachments/assets/11972360-ba0b-4666-8a2e-68a4d557d989)

**Comment by bayunquan** [comment]
![IMG20240728165349](https://github.com/user-attachments/assets/34d6e37f-8759-4805-ad99-878ca7f0ea50)

**Comment by bayunquan** [comment]
incorrect protocol？

**Comment by akiirui** [comment]
注册表没问题，exe 也可以运行，但是浏览器无法正常调用。
我实在是不知道怎么解决的你的问题了，可能是 Firefox 配置问题，也可能是你 Windows 环境问题。
尝试使用 Chrome/Edge？

**Comment by bayunquan** [comment]
![IMG20240728183104](https://github.com/user-attachments/assets/708a0dcc-83a6-44db-bae6-508a178e405e)

**Comment by akiirui** [comment]
> ![IMG20240728183104](https://private-user-images.githubusercontent.com/175550228/352805647-708a0dcc-83a6-44db-bae6-508a178e405e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxNjkyMzQsIm5iZiI6MTcyMjE2ODkzNCwicGF0aCI6Ii8xNzU1NTAyMjgvMzUyODA1NjQ3LTcwOGEwZGNjLTgzYTYtNDRkYi1iYWU2LTUwOGExNzhlNDA1ZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOFQxMjE1MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MDBiZjk3MTAyMTI0YzkxYWQxMjQ2Y2Q3M2EyNDM1MWVlNzE4ODFkYzdlYzkwYWIxOWNlYWIwZGJkYzQ3ZTc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5G7qU3HptN6ivOIH2da7i59v0W19vTVaVQnx0E7dXCg)

虽然在繁体中文 Windows 中资源管理器的路径分隔符是`￥`，但是配置文件里仍然需要使用 `/` 或者 `\\`

**Comment by bayunquan** [comment]
可以用料但B站的影片不能看

**Comment by bayunquan** [comment]
那個mpv顯示黑屏

**Comment by akiirui** [comment]
> 那個mpv顯示黑屏

黑屏？贴出控制台输出和mpv的截图

**Comment by akiirui** [comment]
There have been no new replies for a long time. If you still have this question, reopen it.
