### ISSUE TITLE
Firefox 版本從 v127 更新到 v128 後無法運作

### ISSUE THREAD

**Issue by tenno-lin** [akiirui/mpv-handler#55]
原本在 Firefox v127 運作正常的環境，在更新到 v128 後就無法運作。

以 youtube 為例，https://www.youtube.com/watch?v=GMw539gh328 在點選播放之後，
Firefox 停在這個畫面，但沒有接著執行 mpv.com / mpv.exe：
![2024-07-29 22_47_09-Mozilla Firefox](https://github.com/user-attachments/assets/d855e341-18bc-4ec9-a029-5d23e868e5c7)

已確認過相關設定：
![2024-07-29 22_50_01-設定 — Mozilla Firefox](https://github.com/user-attachments/assets/fc7bd88a-7f8a-44ae-8b63-ae98ec847ab9)
![2024-07-29 22_51_33-D__Tools_MPV_handler_config toml - Notepad++](https://github.com/user-attachments/assets/4cb335dd-ab97-4d2d-8dc1-8d3ea8824868)

為避免 profile / add-ons 的差異，以 PortableApps 的版本仍然可以重現這問題： 
https://sourceforge.net/projects/portableapps/files/Mozilla%20Firefox%2C%20Portable%20Ed./
FirefoxPortable_127.0.2_TradChinese.paf.exe
FirefoxPortable_128.0.3_TradChinese.paf.exe
https://addons.mozilla.org/zh-TW/firefox/addon/violentmonkey/

想請教該怎麼找出問題呢，還請指點，謝謝。

**Comment by akiirui** [comment]
可供参考的信息略少，我在我这里安装一下Firefox看是否能复现。

Windows + Firefox 128 是吧。

**Comment by akiirui** [comment]
我尝试了 Firefox v128 的确和你的情况相同，完全没有弹出选项让你选择使用什么程式打开此链接。
但是我在 `about:config` 中把 `network.protocol-handler.expose-all` 由 `true` 改为 `false` 就可以工作了。
可能是 Firefox 上游修改了什么导致的，可以尝试用以上办法解决或者是给 Firefox 提交 Issue。

**Comment by tenno-lin** [comment]
問題解決了，十分感謝！

**Comment by akiirui** [comment]
请看我修改后的内容，然后恢复 `network.protocol-handler.expose-all` -> `true` 然后按照后面的操作。

**Comment by akiirui** [comment]
不过我还是认为是 Firefox 上游修复其他安全问题的时候影响了这部分功能的正常工作。
似乎其他协议链接也是同样的状况，reddit 上有一个更新后无法打开 magnet 磁力链接的，情况和这个问题一样点击链接只是打开一个空白的标签页。
https://www.reddit.com/r/Piracy/comments/1e17p7j/firefox_not_opening_magnet_links_since_update/

**Comment by tenno-lin** [comment]
收到，再次感謝！

**Comment by shmilee** [comment]
添加选项 `network.protocol-handler.expose.mpv=false` 解决了相同的问题，火狐版本129。

在**添加选项之前**，我试过以下三个mpv://协议+火狐v129+一个处理 mpv:// 协议的lua脚本，只有配合 mpv-handler 的 js 脚本会打开一个mpv://新标签页，然后调用 mpv-handler。其他两个没有打开新标签页的过程。
* 卡在新标签页，必须手动地址栏回车才会询问打开， https://github.com/akiirui/mpv-handler
* 正常，https://github.com/LuckyPuppy514/Play-With-MPV
* 正常，https://github.com/Baldomo/open-in-mpv

所以在火狐128版本之后，mpv-handler js 脚本因为卡在了新标签页这个多出来的过程，所以不能自动工作了。
添加以上选项后，新标签页不再出现，问题解决。

试着找了两行代码（还有一个js代码太长了，没找），js不熟，找错了就忽略吧。不知道上面的问题是不是和 `buttonPlay`的click有关？
https://github.com/akiirui/userscript/blob/9b0e5849d555641942db6a3589ec0233821553f8/userscript.js#L406-L409
https://github.com/Baldomo/open-in-mpv/blob/fd25fc60e51156a282d0c168d6635a72eadae230/extension/Chrome/common.js#L103

**Comment by akiirui** [comment]
@shmilee 你可以尝试删除Firefox的哪项参数然后在油猴管理器里删掉脚本的 
`    buttonPlay.target = "_blank";`
这一行测试一下

**Comment by shmilee** [comment]
@akiirui 删掉 _blank 这行后，火狐不添加那项也能正常工作。

**Comment by akiirui** [comment]
> @akiirui 删掉 _blank 这行后，火狐不添加那项也能正常工作。

已删除该行。
