### ISSUE TITLE
Failed to run player (文件名、目录名或卷标语法不正确。 (os error 123))

### ISSUE THREAD

**Issue by phyrevue** [akiirui/mpv-handler#60]
测试运行报错:
Playing: https://www.bilibili.com/video/BV1Vu4y1v7CF/
Failed to run player (文件名、目录名或卷标语法不正确。 (os error 123))

配置文件截图:
![Snipaste_2024-09-19_12-48-18](https://github.com/user-attachments/assets/31588396-afa7-4435-9fa3-27390dbe8686)
报错截图：
![Snipaste_2024-09-19_12-45-00](https://github.com/user-attachments/assets/49620dc8-f57c-4895-8968-9984f4ad48d7)
MPV截图：
![Snipaste_2024-09-19_12-47-01](https://github.com/user-attachments/assets/3916a9ef-5f73-4793-afe5-1b154cc1338e)

**Comment by akiirui** [comment]
I can't reproduce it, please check whether the quotes in your value are half-width English quotes.

**Comment by akiirui** [comment]
Okay, I see your config.toml from edit hisotry.

![1](https://github.com/user-attachments/assets/449538d4-07b4-41b8-aa70-064fac07cead)

I have a question, Where did you copy the paths from? They have an invisible character. https://www.compart.com/en/unicode/U+202A

Please delete the characters in quotation marks and re-enter.

Done.

**Comment by phyrevue** [comment]
the problem is solved and it works successfully

i copy the paths from here
![Snipaste_2024-09-19_21-33-33](https://github.com/user-attachments/assets/af72d6a7-5179-48f2-814f-b84ce1bbc9a9)

**Comment by akiirui** [comment]
Yes, it can be reproduced. The path copied here has invisible characters.
I suggest you enter path manually, or change to an editor that can show characters (such as Visual Studio Code)
