### ISSUE TITLE
不知什么原因出错

### ISSUE THREAD

**Issue by ppqcool-1988** [akiirui/mpv-handler#61]
> [ytdl_hook] ERROR: [BiliBili] 1zH4y1D77x: Unable to download JSON metadata: HTTP Error 412: Precondition Failed (caused by <HTTPError 412: Precondition Failed>)
[ytdl_hook] youtube-dl failed: unexpected error occurred
Failed to recognize file format.

**Comment by akiirui** [comment]
yt-dlp 坏了，B站无法解析，等修吧。
与 mpv-handler 无关。
