### ISSUE TITLE
Support title parameter

### ISSUE THREAD

**Issue by ycs77** [akiirui/mpv-handler#62]
Could you support the `title` parameter for mpv-handler from mpv `--title`? Because the title sometimes always shows the `playlist.m3u8` from the URL, I want to customize it. And thanks for your package helping me🥰

The `--title` option reference: https://github.com/mpv-player/mpv/blob/53f2619dbd740b71bdd4277f096d077ffb8d571b/DOCS/man/options.rst#window

**Comment by akiirui** [comment]
mpv-handler doesn't do this work. The title is obtained by yt-dlp parsing the URL or mpv parsing the video file.
I am not sure about your use case.
If you play a video from the website supported by yt-dlp but do not get the correct title, please go to yt-dlp to give feedback.

**Comment by ycs77** [comment]
I don't use `yt-dlp`.

I have a playlist containing the video's m3u8 URL, the title now only gets from the video path, and each video is shown the title `playlist.m3u8`:

```
https://example.com/aaa/playlist.m3u8
https://example.com/bbb/playlist.m3u8
https://example.com/other/playlist.m3u8
```

Now open the video basic example mpv command like this:

```bash
mpv https://example.com/aaa/playlist.m3u8
mpv https://example.com/bbb/playlist.m3u8
mpv https://example.com/other/playlist.m3u8
```

![Screenshot 2024-09-29 011612](https://github.com/user-attachments/assets/85151bd2-c0b5-420f-bdaf-719c41fd300a)

And the custom video title of the mpv command like this

```bash
mpv https://example.com/aaa/playlist.m3u8 --title="A custom title"
mpv https://example.com/bbb/playlist.m3u8 --title="B custom title"
mpv https://example.com/other/playlist.m3u8 --title="My custom title"
```

![Screenshot 2](https://github.com/user-attachments/assets/d86a90e3-3aa7-4334-bb71-c76acfdfcf3a)

So I want to support the custom title parameter for the mpv-handler.

**Comment by akiirui** [comment]
So, you have a self maintenance userscript to support some special sites?

**Comment by ycs77** [comment]
> So, you have a self maintenance userscript to support some special sites?

Yes.

**Comment by akiirui** [comment]
I have implemented this feature, but when testing it I found that --title does not work when the video stream in the m3u8 already has title metadata.

![Screenshot From 2024-09-29 05-24-17](https://github.com/user-attachments/assets/b7750bf7-843c-4a77-8e6e-7b2b1630c310)

Can you provide an m3u8 example showing only the filename?
I'm wondering if this feature is really necessary?

**Comment by ycs77** [comment]
I implemented this feature in #64, but this is my first writing the Rust, I have some shortcomings, please adjust them better.

**Comment by akiirui** [comment]
Done, please try `v_title` option. You should encode title by url-safe base64.

**Comment by ycs77** [comment]
Thanks!

And now is have another bug. If the `v_title` contains Chinese characters will throw the error `InvalidCharacterError: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.`, so I'll use the other method instead the `btoa()` function, final I require the package [`js-base64`](https://www.npmjs.com/package/js-base64) into my user script to solve this problem.

```js
// ==UserScript==
// ...
// @require      https://cdn.jsdelivr.net/npm/js-base64@3.7.7/base64.min.js
// ==/UserScript==

// this will throw `InvalidCharacterError`
let data = btoa("你好，世界");

// change to this will be solved
let data = Base64.encode("你好，世界");

let safe = data.replace(/\//g, "_").replace(/\+/g, "-").replace(/\=/g, "");
```

I think adding this solution to README will be better, let others know about this situation.

**Comment by akiirui** [comment]
It's just a simple example. You can use the js-base64 library, but it's not the only way.

**Comment by ycs77** [comment]
I see. Thanks for your reply!
