### ISSUE TITLE
能否开发使用aria2播放天翼云、阿里云这些云盘的视频

### ISSUE THREAD

**Issue by Sailing168** [akiirui/mpv-handler#8]

**Comment by akiirui** [comment]
完全不能理解你的需求。
 
`aria2` 是个下载工具，无法播放视频。

**Comment by Sailing168** [comment]
我的需求就是使用本地播放器播放云端视频，没想到会无法理解。
你应该没听说xiaobaiyang项目，别人就能使用mpv播放webdav的云端视频

Akatsuki Rui ***@***.***> 于2021年4月23日周五 上午7:42写道：

**Comment by akiirui** [comment]
> 我的需求就是使用本地播放器播放云端视频

请检查你的提问，`aria2` 播放云盘视频？`aria2` 是一个下载工具，不是播放器。

> 别人就能使用mpv播放webdav的云端视频

`mpv-hander` 只是一个提供 protocol 转接 `mpv` 的工具，具体播放网页视频需要配合 userscript。

参见 https://github.com/akiirui/userscript/tree/play-with-mpv-handler
