### ISSUE TITLE
Can't upgrade to new version

### ISSUE THREAD

**Issue by Slartibaal** [akiirui/mpv-handler#9]
Whenever I try to upgrade or build the new version I get this error: no override and no defaul toolchain set.

**Comment by akiirui** [comment]
Can you tell me more information? OS, Rust version, and what did you do?

**Comment by akiirui** [comment]
Okay, maybe i found what cause this issue.

You are using `rustup` and not set default toolchain, That is a omission of PKGBUILD, I will push new PKGBUILD to AUR.

Ref: https://aur.archlinux.org/packages/himalaya-git/#comment-804053

**Comment by akiirui** [comment]
And I recommend you to use `extra/rust` instead of `community/rustup`.

The `rustup` will store data more than 1 GiB in your `$HOME/.rustup` and `$HOME/.cargo`. And these data will not be automatically cleaned up after you uninstall rustup.

But another one `rust` doesn't store these data.

**Comment by akiirui** [comment]
Fixed:
- mpv-handler: https://aur.archlinux.org/cgit/aur.git/commit/?h=mpv-handler&id=f47724674034997d3c90c3946e9e9efb910c00a8
- mpv-handler-git: https://aur.archlinux.org/cgit/aur.git/commit/?h=mpv-handler-git&id=c6572819d9eb9ab34986fd5fbb7a224a87275af8

**Comment by Slartibaal** [comment]
Fixed, thank you.
